// Generated by dts-bundle v0.4.3
// Dependencies for this module:
//   ../../express

declare module 'alliance/core' {
    export { Application } from 'alliance/core/decorators/core/application';
    export { Inject } from 'alliance/core/decorators/core/inject';
    export { Controller } from 'alliance/core/decorators/core/controller';
    export { Route } from 'alliance/core/decorators/core/route';
    export { PathVariable } from 'alliance/core/decorators/core/pathVariable';
    export { RequestParam } from 'alliance/core/decorators/core/requestParam';
    export { BodyParam } from 'alliance/core/decorators/core/bodyParam';
    export { AbstractController } from 'alliance/core/components/core/controller/abstractController';
    export { Log } from 'alliance/core/components/core/debug/log';
}

declare module 'alliance/core/decorators/core/application' {
    export function Application(target: any): void;
}

declare module 'alliance/core/decorators/core/inject' {
    export function Inject(target: any, propertyKey: string | symbol, parameterIndex?: number): void;
}

declare module 'alliance/core/decorators/core/controller' {
    export function Controller(target: any): void;
}

declare module 'alliance/core/decorators/core/route' {
    export const allianceRoutes: symbol;
    export const allianceBasePath: symbol;
    export interface allianceRoute {
        path: string;
        key: string;
    }
    export function Route(path: string, methods?: string[]): (target: any, key?: string, descriptor?: TypedPropertyDescriptor<any>) => void;
}

declare module 'alliance/core/decorators/core/pathVariable' {
    export function PathVariable(target: Object, propertyKey: string | symbol, parameterIndex: number): void;
}

declare module 'alliance/core/decorators/core/requestParam' {
    export function RequestParam(target: Object, propertyKey: string | symbol, parameterIndex: number): void;
}

declare module 'alliance/core/decorators/core/bodyParam' {
    export function BodyParam(target: Object, propertyKey: string | symbol, parameterIndex: number): void;
}

declare module 'alliance/core/components/core/controller/abstractController' {
    import * as express from 'express';
    export abstract class AbstractController {
        template: string;
        renderVariables: Object;
        context: Object;
        app: express.Express;
        response: express.Response;
        request: express.Request;
        meta: any;
        constructor();
        set(key: string | Object, value?: string): void;
    }
}

declare module 'alliance/core/components/core/debug/log' {
    export class Log {
        static message(...message: any[]): void;
        static warning(...message: any[]): void;
        static error(...message: any[]): void;
        static success(...message: any[]): void;
        static event: {
            warning: string;
            error: string;
            info: string;
            request: string;
        };
    }
}

