// Generated by dts-bundle v0.4.3

declare module 'alliance/shell' {
    export class AbstractShell {
    }
    export function Shell(name: string, options: any): (target: any, key: any) => void;
    export function Command(target: any): (target: any, key: any) => void;
}

